### ISSUE TITLE
chromebook-veyron builds but will not boot "kernel.bin: No such file or directory"

### ISSUE THREAD

**Issue by SolidHal** [offensive-security/kali-arm-build-scripts#100]
HostOS: Kali Linux latest (ran apt-get update, upgrade, and dist-upgrade)

Possibly related Errors from the log: 
> I: Keyring file not available at /usr/share/keyrings/kali-archive-keyring.gpg; switching to https mirror https://deb.debian.org/debian

> dd: failed to open '/root/arm-stuff/kali-arm-build-scripts/veyron-2.12/kernel.bin': No such file or directory

>mm/filemap.c: In function ‘wait_on_page_bit_killable_timeout’:
> mm/filemap.c:587:9: warning: passing argument 3 of ‘__wait_on_bit’ from incompatible pointer type [enabled by default]
> In file included from include/linux/fs.h:6:0,
>                  from mm/filemap.c:14:
> include/linux/wait.h:155:5: note: expected ‘int (*)(void *)’ but argument is of type ‘int (*)(struct wait_bit_key *)’

> 
> fs/ext4/inode.c: In function ‘ext4_setattr’:
> fs/ext4/inode.c:4702:2: error: #error POSIX_ACL not supported in 3.18 backport
> scripts/Makefile.build:308: recipe for target 'fs/ext4/inode.o' failed
> make[2]: *** [fs/ext4/inode.o] Error 1
> scripts/Makefile.build:455: recipe for target 'fs/ext4' failed
> make[1]: *** [fs/ext4] Error 2
> Makefile:865: recipe for target 'fs' failed
> make: *** [fs] Error 2

After writing the image to usb, the chromebook refuses to boot from the device all together. I have booted Archlinux successfully. I can also boot the prebuilt kali 2.1.2 image, however after it finishes the initial verbose loading it goes to a black screen but that's at least farther than this gets. I'm using these scripts because I wanted try try older versions to see if they boot without going to a black screen, but now I'm stuck with images that appear to not have a kernel. 

full build log:
[veyron_log.txt](https://github.com/offensive-security/kali-arm-build-scripts/files/880980/veyron_log.txt)

EDIT: *prebuilt not rebuilt

**Comment by steev** [comment]
The image won't fail building because of the kernel failing to build, but as you noticed, the kernel didn't successfully compile (so no, the image won't boot, because there is no kernel to build)

That said, it looks like they've done something with a back port that breaks POSIX_ACL in the kernel and until that's fixed, the image won't boot properly.  I'm currently working on this and hope to have a fix pushed soon.

**Comment by SolidHal** [comment]
That makes sense. Would using an older release of kali work as a temporary workaround? 
Also, does it not cause issues with building if it choose to get some of the packages from the debian mirror instead of the kali mirror? I feel like I had read somewhere that it doesn't work properly if the kali mirror isn't used.

**Comment by SolidHal** [comment]
Theres also this string of errors from the log that may or may not be useful:
> Setting up fuse (2.9.7-1) ...
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/cpuid/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/fuse/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/nfnetlink_queue/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/nfnetlink_log/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/nfnetlink/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/bluetooth/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/rfkill/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/ppdev/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/joydev/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/intel_powerclamp/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/intel_rapl_perf/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/evdev/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/pcspkr/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/serio_raw/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/sg/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/binfmt_misc/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/snd_intel8x0/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/battery/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/parport_pc/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/parport/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/video/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/ac/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/snd_ac97_codec/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/button/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/ac97_bus/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/snd_pcm/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/snd_timer/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/snd/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/soundcore/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/acpi_cpufreq/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/tpm_tis/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/tpm_tis_core/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/tpm/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/ip_tables/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/x_tables/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/autofs4/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/ext4/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/crc16/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/jbd2/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/crc32c_generic/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/fscrypto/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/ecb/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/mbcache/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/hid_generic/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/usbhid/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/hid/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/sr_mod/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/cdrom/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/sd_mod/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/ata_generic/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/ohci_pci/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/crct10dif_pclmul/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/crc32_pclmul/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/crc32c_intel/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/ghash_clmulni_intel/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/aesni_intel/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/aes_x86_64/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/lrw/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/gf128mul/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/glue_helper/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/ablk_helper/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/cryptd/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/psmouse/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/ahci/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/libahci/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/i2c_piix4/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/ehci_pci/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/ohci_hcd/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/ehci_hcd/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/usbcore/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/usb_common/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/ata_piix/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/e1000/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/libata/holders': No such file or directory
> libkmod: ERROR ../libkmod/libkmod-module.c:1929 kmod_module_get_holders: could not open '/sys/module/scsi_mod/holders': No such file or directory

**Comment by steev** [comment]
it can be ignored.

**Comment by steev** [comment]
The kernel build has nothing to do with kali v debian repositories.  Upstream (Chrome/Chromium) kernel devs did something very stupid, and broke POSIX ACL pulling in some things to support Android on ChromeOS. 

The immediate fix is to edit the chromebook-rockchip... file in kernel-configs and set the line that has (roughly) 'CONFIG_EXT4_POSIX_ACL=y' to be '# CONFIG_EXT4_POSIX_ACL is not set'

I've only tested that it compiles, not any Kali interaction just yet, I'm currently building the image to test it.

You can definitely still use an older Kali image, and just update the software via apt update && apt dist-upgrade, it will just take a long time as there are a lot of packages that have been updated/changed since the last release.

**Comment by tvondra** [comment]
I've managed to get the veyron images working, after a bit of struggle. I know @steev probably already fixes most of the issues in his repository, so I'm not going to send pull requests - if needed, look at this branch: https://github.com/tvondra/kali-arm-build-scripts/tree/fixes

In general, it works. One thing I ran into is that after restart I have to reinstall qemu-user-static package, otherwise I get "Exec format error" when the shell script runs debootstrap. Apparently the qemu-arm gets empty or something.

I intend to use the image on my C201PA chromebook, and while I haven't done much testing yet the image seems to be running OK, with one exception - logging out from from xfce freezes the screen for a while. I assume it's something about the GPU, perhaps.

One change that is not merely a fix is enabling all available encryption algorithms in kernel. That's pretty much the reason why I started looking into building custom images, because I want/need to use LUKS, and that doesn't work with the default kernel.

@steev, Let me know if you're OK with adding this to the official image, and if you need a pull request.

**Comment by steev** [comment]
I've seen the same issue, and it's definitely kernel side.

I looked through some of your changes, and they seem to be okay - I've actually already integrated some of the config changes (although I may not enable everything that you have) - once I finish what I'm working on and push it, please take a look and compare to yours.  Pull requests are always appreciated though!

**Comment by tvondra** [comment]
Hi, any progress on this? Is there a way to help moving it forward?

**Comment by steev** [comment]
This is working now - the issue was (and is) upstream's kernel support for Android breaks ACLs for ext4.  The only solution is to disable them, which is done in the latest image.
