### ISSUE TITLE
SSH is not working | bbb image 2017.01

### ISSUE THREAD

**Issue by dimonik** [offensive-security/kali-arm-build-scripts#104]
I wrote 
[kali-2017.01-bbb.img](https://images.offensive-security.com/arm-images/kali-2017.01-bbb.img.xz)
 to microSD card,
inserted it into BeagleBoneBlack.

Pings are successful, but i can't do SSH.
ssh: connect to host 192.168.1.11 port 22: Connection timed out
sshd_config has PermitRootLogin==Yes.

I don't have keyboard, mouse, monitor. How can I enable SSH?

P.S. Actually, the same issue was seen on kali-2.0.1-bbb.img and there is [article on how to fix](http://www.brunoc.org/kali-2-0-on-a-beaglebone-black/) but it is not applicable to 2017.01 image.

**Comment by dimonik** [comment]
I found the reason: corrupted micro SD card. So it is hardware error.

**Comment by dimonik** [comment]
The reason why SSH is not working is #105

**Comment by steev** [comment]
I am going to close this issue since the real issue is in #105
