### ISSUE TITLE
latest official build scripts?

### ISSUE THREAD

**Issue by tothi** [offensive-security/kali-arm-build-scripts#110]
odroid-c2.sh found here in the repo is surely not the one which built the official 2017.1 image found here: https://www.offensive-security.com/kali-linux-arm-images/ (as ODROID-C2 (arm64) ).

this script is from "Merge 2.1.2" Mar 18 2016 (without major updates).

the hosted image contains a newer kernel version (and other mods).

does anybody know where are the official (current) build scripts? :)

fyi: forked and updated odroid-c2.sh to make building work now, even on other distros than kali (tested on gentoo), and updated kernel config from the official image (so the kernel compiles and runs well).

https://github.com/tothi/kali-arm-build-scripts

probably i'll make a pull request to the official repo soon...

**Comment by steev** [comment]
Sorry tothi, I forgot to push the 2017.1 bits, but 2017.2 is in the repo now.  Can you check if there is anything that you added that isn't in?
