### ISSUE TITLE
Raspberry 3 mod B 

### ISSUE THREAD

**Issue by satoribeats** [offensive-security/kali-arm-build-scripts#124]
Issues getting it to work.  Try'd all three versions on the website.  2.8 tft touch screen .  Thank you!

**Comment by steev** [comment]
The only image that support the rpi3 at the moment is the rpi3-nexmon script.  You'll need to manually set up the 2.8 tft touch screen on it.

**Comment by hoenheim93** [comment]
and for the model raspberry pi 3 B+ ?

**Comment by threeway** [comment]
The 3b+ is supported by the rpi3 image

**Comment by hoenheim93** [comment]
ok thanks , i flash sd  32 go now , after install kali ,how i can install lcd 3.5 (kuman)

**Comment by hoenheim93** [comment]
1rst log , oblige use keyboard with usb ? not bluethooth ?

**Comment by threeway** [comment]
I would suggest it since typically to pair a Bluetooth keyboard, you need do some setup. 

Please note, this is not a support forum for how to use the devices, you should be using the forums or IRC for that. 

This is more of a bug report/feature request for the scripts used to build the images

**Comment by hoenheim93** [comment]
ok no worries you was very helpful, +1 and thank you again

**Comment by hoenheim93** [comment]
?

**Comment by steev** [comment]
Not private message.  Post to the forums - forums.kali.org or the #kali-linux irc channel on irc.freenode.net

**Comment by hoenheim93** [comment]
Thank’s i go now
