### ISSUE TITLE
Simple Kali arm build script for Raspberry pi 3 b+

### ISSUE THREAD

**Issue by MrSuicideParrot** [offensive-security/kali-arm-build-scripts#133]
The script to build  the Kali raspberry image, ``` rpi.sh```, when applied to a raspberry pi 3 b+  doesn't show the wifi interface. The nexmon script show the wifi interface, but with the nexmon firmware for the wifi. Could you build a image with the default firmware for the wifi?

**Comment by threeway** [comment]
The rpi2.sh script would be the one you’re after.

**Comment by threeway** [comment]
Also, in the 2018.3 release (and in the rpi3-nexmon script currently) we put both the nexmon and the original firmware. So you can switch to the original firmware if you like.

**Comment by MrSuicideParrot** [comment]
Thank you, very much!!
