### ISSUE TITLE
Odroid U2 image does not include "u2" in image name 

### ISSUE THREAD

**Issue by hartzell** [offensive-security/kali-arm-build-scripts#152]
I have an Odroid U3 and the Kali pages suggest that it will run on the U2 image.

There's no U2 image on the download site (https://www.offensive-security.com/kali-linux-arm-images/), but a bit of "process of elimination" and reading build scripts suggest that the `odroid-u2.sh` script builds the image that the download site simply calls "Kali Linux ODROID" and links to [this image with the simple name "odroid"](https://images.offensive-security.com/arm-images/kali-linux-2018.4-odroid.img.xz).

If this is, indeed, the U2 image, would it be possible to touch up [line 22 of the `odroid-u2.sh` build script](https://github.com/offensive-security/kali-arm-build-scripts/blob/fa46deb78d34e8470714818196016088167169ca/odroid-u2.sh#L22)  to include the model name?

**Comment by steev** [comment]
I agree that the naming is a bit ambiguous.  I'll see about updating the image name on the releases page to include U2/U3 in it for the next release!

**Comment by hartzell** [comment]
Sounds great.  Thanks for putting all this together and sharing it.  Was hoping to return w/ a success story with the U3, but....

Booted part way once until it stopped with a complaint from uboot saying

> [...] ext4fs_devread read outside partition 158953840

I re-dd'ed the image, now it won't boot at all.  Thinking the card might be shot.  We'll see.
