### ISSUE TITLE
Odroid image: read outside partition

### ISSUE THREAD

**Issue by hartzell** [offensive-security/kali-arm-build-scripts#153]
I'm trying to run Kali 2018.4 on an Odroid U3+.

Booting fails like so:

```
OK

U-Boot 2010.12-00000-g33e05ff-dirty (Oct 17 2018 - 17:35:30) for Exynox4412


CPU: S5PC220 [Samsung SOC on SMP Platform Base on ARM CortexA9]
APLL = 1000MHz, MPLL = 880MHz
DRAM:  2 GiB

PMIC VERSION : 0x00, CHIP REV : 3
TrustZone Enabled BSP
BL1 version: 20121128


Checking Boot Mode ... SDMMC
MMC Device 0: 15193 MB
*** Warning - using default environment

In:    serial
Out:   serial
Err:   serial
ModeKey Check... run normal_boot 
Net:   usb_ether
Hit any key to stop autoboot:  0 
Cable not connected or failed to initialize.
Failed to mount ext2 filesystem...
ext4fs_devread read outside partition 158953840
```

I believe that it's suffering from the same problem that you fixed for CuBox Kali in #106, as originally described in [this StackExchange question](https://unix.stackexchange.com/questions/304158/u-boot-2016-07-ext4fs-devread-read-outside-partition).

I'm not set up to build ARM images.  If you can spin up an image with that change for the Odroid U2/U3/U3+, I'll be happy to test it.

**THANKS**!

**Comment by hartzell** [comment]
I think that the fix will be doing the same thing you did for cubox, [here on line 283](https://github.com/offensive-security/kali-arm-build-scripts/blob/master/cubox.sh#L283) for the Odroid-U2 [here on line 316](https://github.com/offensive-security/kali-arm-build-scripts/blob/master/odroid-u2.sh#L316).

**Comment by steev** [comment]
I've added it in 11714da46c7a950c8038c9d70733b049ed122ba6 - do me a favor and shoot me into an email to Steev at kali dot org so I have your email address please?
