### ISSUE TITLE
efikamx apt-get install

### ISSUE THREAD

**Issue by wallneradam** [offensive-security/kali-arm-build-scripts#31]
The efikamx.sh build script fails with the following error:
E: Unable to locate package arachni
Because of this the image is pretty unusable. Nothing is working, no network, no GUI. Even the downloadable version on the homepage is bad.

Removing arachni solves the problem.
Thanks for your hard work on this.

**Comment by steev** [comment]
Correct.  The scripts aren't particularly error resistant.  I'm going to be pushing the scripts soon that are part of 1.1.1 being released (I apologize for not pushing more often when I fix things like this) soon and this will go away.
