### ISSUE TITLE
How to enable/load dtoverlay in kali rpi

### ISSUE THREAD

**Issue by sphonala** [offensive-security/kali-arm-build-scripts#40]
hiiiii,
        i am working on rpi kali linux. i am able to boot kali linux(4.0.9) with rpi b+ on tft3.5 (using fbtft). Now i want to enable ads7846 touch-screen on same. i am not able to enable ads7846-overlay.dtb. there is no any config.txt file in boot folder. how  can i enable/load dt overlay. i have done this on raspbian by enabling through /boot/config.txt & its working.  
i also try to enable through /etc/modules but its not working.
ads7846 model=7843 gpio_pendown=3 pressure_max=255 x_plate_ohms=100 swap_xy=1 x_min=230 x_max=3850 y_min=190 y_max=3850 settle_delay_usecs=200 penirq_recheck_delay_usecs=1000

thnks.

**Comment by steev** [comment]
you can create the config.txt manually just like it would be in raspian.

also, with systemd, module options go into a .conf file in /etc/modprobe.d/ (see: e.g. /etc/modprobe.d/pitft.conf 

This is really better suited to have been posted on the forums not the issue tracker, but I do hope the above information helps!
