### ISSUE TITLE
Build script for porting Kali linux to Xilinx Zynq ZC702 Board

### ISSUE THREAD

**Issue by Abhinav-Biswas** [offensive-security/kali-arm-build-scripts#44]
I am trying to port kali linux to xilinx zynq zc702 board as per the following link, with a difference that i want to use kali rootfs instead of ubuntu rootfs.
http://www.wiki.xilinx.com/Zynq-7000+AP+SoC+-+Installing+the+Ubuntu+Desktop+on+PetaLinux+and+Demo+Tech+Tip

I am directly using the precompiled boot partition given on the above link. 
The boot partition contains BOOT.BIN, uImage & devicetree.dtb

Instead of using the linaro ubuntu rootfs,
I cross-compiled kali rootfs with the following script:
[script.txt](https://github.com/offensive-security/kali-arm-build-scripts/files/52755/script.txt)

But, I am unable to login to the system with default username/password: root/toor
Here is the serial console output.
[Output.txt](https://github.com/offensive-security/kali-arm-build-scripts/files/52756/Output.txt)

Please help whether I need to modify kernel options or rootfs partition needs some extra configuration parameters. Is anything missing in the kali root file system?

**Comment by steev** [comment]
If you are using their prebuilt kernel (uImage and devicetree.dtb) then be sure you extract/copy their modules into the correct path in the Kali rootfs.

Other than that... the script seems to be correct, the only thing I could guess is, what is the serial console listed as ON the zc702?  You possibly need to add that device to /etc/securetty to allow root login on the serial console.
