### ISSUE TITLE
bbb.sh - kernel source doesnt exist anymore

### ISSUE THREAD

**Issue by 0xicl33n** [offensive-security/kali-arm-build-scripts#45]
Line 202 - `git clone --depth 1 --branch am33x-v3.8 https://github.com/RobertCNelson/linux-dev ${basedir}/kernel`

Branch am33x-v3.8 does not exist 

https://github.com/RobertCNelson/bb-kernel/tree/am33x-v3.8

I will try building an image with this source now, but i dont know what will happen.

UPDATE: Did not build. Image not created. These scripts need to be majorly updated

**Comment by steev** [comment]
They will be - I was in the process of building and testing the release based on kali-rolling.  Appreciate the report though!  The new one is based on the master branch of linux-dev which uses a 4.4 kernel.

**Comment by 0xicl33n** [comment]
Sounds good & cant wait! Could you possibly do something about ssh as root being disabled on boot because some of us dont have microhdmi cables to connect the board up to a monitor and get in there manually

**Comment by steev** [comment]
Yep, that's one of the fixes coming with 2.1 as well :)

**Comment by duchengyao** [comment]
New Kernel，like it !
