### ISSUE TITLE
bbb: Unable to display the icon after dist-upgrade

### ISSUE THREAD

**Issue by duchengyao** [offensive-security/kali-arm-build-scripts#51]
I'm using the latest version of the mirror, found it impossible to display icons after `dist-upgrade`.

![wp_20160204_17_20_05_raw_li](https://cloud.githubusercontent.com/assets/7941237/12811080/1cb13d0a-cb65-11e5-840e-7686d02343a6.png)

By the way, is this kind of issue should be post here?
Are there other places can I post?

Best regards.

**Comment by steev** [comment]
This belongs on the kali bug tracker as it's not an issue with the script itself.

**Comment by duchengyao** [comment]
Thanks! @steev
