### ISSUE TITLE
rpi2.sh - cmdline.txt - missing ttyAMA0

### ISSUE THREAD

**Issue by bubbasnmp** [offensive-security/kali-arm-build-scripts#54]
cmdline.txt for rpi2 missing info for ttyAMA0.
The rpi image works out of the box. :-)
The getty entry seems to be ok for both of them.

https://github.com/offensive-security/kali-arm-build-scripts/blob/master/rpi2.sh

# Create cmdline.txt file
cat << EOF > ${basedir}/bootp/cmdline.txt
dwc_otg.fiq_fix_enable=2 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 rootwait rootflags=noload
EOF

# Enable login over serial
echo "T0:23:respawn:/sbin/agetty -L ttyAMA0 115200 vt100" >> ${basedir}/root/etc/inittab

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
https://github.com/offensive-security/kali-arm-build-scripts/blob/master/rpi.sh

# Create cmdline.txt file
cat << EOF > ${basedir}/bootp/cmdline.txt
dwc_otg.lpm_enable=0 console=ttyAMA0,115200 kgdboc=ttyAMA0,115200 console=tty1 elevator=deadline root=/dev/mmcblk0p2 rootfstype=ext4 rootwait
EOF

# Enable login over serial
echo "T0:23:respawn:/sbin/agetty -L ttyAMA0 115200 vt100" >> ${basedir}/root/etc/inittab

**Comment by steev** [comment]
Thanks for pointing that out.  I've updated the script and pull request was made.  Since this is just a matter of editing a text file on the rpi2, I'm not going to release a new image for it with that one change.
