### ISSUE TITLE
debootstrap fails to --second-stage on kali-rolling

### ISSUE THREAD

**Issue by crazypenguin** [offensive-security/kali-arm-build-scripts#57]
run rpi2.sh
after:
debootstrap --foreign --arch $architecture kali-rolling kali-$architecture http://$mirror/kali
there have apt deb package in var subdirectory,but not been unpacked
so,when chroot in and run "apt-get update" during the rpi2.sh,it will output apt-get not found
please help me.

**Comment by steev** [comment]
Can you give the full output of the script when you run it please?

You shouldn't have to chroot in, so I'm not sure what you mean here.

**Comment by crazypenguin** [comment]
➜  kali-arm-build-scripts git:(master) ./rpi2.sh 2.0
I: Retrieving Release
I: Retrieving Release.gpg
I: Checking Release signature
I: Valid Release signature (key id 44C6513A8E4FB3D30875F758ED444FF07D8D0BF6)
I: Retrieving Packages
I: Validating Packages
I: Resolving dependencies of required packages...
I: Resolving dependencies of base packages...
I: Found additional required dependencies: adduser dmsetup insserv libapparmor1 libaudit-common libaudit1 libbz2-1.0 libcap2 libcap2-bin libcryptsetup4 libdb5.3 libdebconfclient0 libdevmapper1.02.1 libgcrypt20 libgpg-error0 libkmod2 libncursesw5 libseccomp2 libsemanage-common libsemanage1 libsystemd0 libudev1 libustr-1.0-1 systemd systemd-sysv
I: Found additional base dependencies: libdns-export100 libffi6 libgmp10 libgnutls-openssl27 libgnutls30 libhogweed4 libicu55 libidn11 libisc-export95 libjson-c2 liblz4-1 libmnl0 libnetfilter-acct1 libnettle6 libnfnetlink0 libp11-kit0 libpsl0 libtasn1-6
I: Checking component main on http://http.kali.org/kali...
I: Retrieving adduser 3.113+nmu3
I: Validating adduser 3.113+nmu3
I: Retrieving apt 1.2.3
I: Validating apt 1.2.3
I: Retrieving apt-utils 1.2.3
I: Validating apt-utils 1.2.3
I: Retrieving base-files 1:2016.1.0
I: Validating base-files 1:2016.1.0
I: Retrieving base-passwd 3.5.39
I: Validating base-passwd 3.5.39
I: Retrieving bash 4.3-14+b1
I: Validating bash 4.3-14+b1
I: Retrieving bsdmainutils 9.0.6+b1
I: Validating bsdmainutils 9.0.6+b1
I: Retrieving bsdutils 1:2.27.1-3
I: Validating bsdutils 1:2.27.1-3
I: Retrieving coreutils 8.24-1
I: Validating coreutils 8.24-1
I: Retrieving cpio 2.11+dfsg-4.1
I: Validating cpio 2.11+dfsg-4.1
I: Retrieving cron 3.0pl1-128
I: Validating cron 3.0pl1-128
I: Retrieving dash 0.5.8-2.1
I: Validating dash 0.5.8-2.1
I: Retrieving debconf 1.5.58
I: Validating debconf 1.5.58
I: Retrieving debconf-i18n 1.5.58
I: Validating debconf-i18n 1.5.58
I: Retrieving debian-archive-keyring 2014.3
I: Validating debian-archive-keyring 2014.3
I: Retrieving debianutils 4.7
I: Validating debianutils 4.7
I: Retrieving diffutils 1:3.3-3
I: Validating diffutils 1:3.3-3
I: Retrieving dmidecode 3.0-2
I: Validating dmidecode 3.0-2
I: Retrieving dmsetup 2:1.02.115-2
I: Validating dmsetup 2:1.02.115-2
I: Retrieving dpkg 1.18.4
I: Validating dpkg 1.18.4
I: Retrieving e2fslibs 1.42.13-1
I: Validating e2fslibs 1.42.13-1
I: Retrieving e2fsprogs 1.42.13-1
I: Validating e2fsprogs 1.42.13-1
I: Retrieving emdebian-archive-keyring 2.0.5
I: Validating emdebian-archive-keyring 2.0.5
I: Retrieving findutils 4.6.0+git+20160126-2
I: Validating findutils 4.6.0+git+20160126-2
I: Retrieving gcc-4.8-base 4.8.5-4
I: Validating gcc-4.8-base 4.8.5-4
I: Retrieving gcc-4.9-base 4.9.3-10
I: Validating gcc-4.9-base 4.9.3-10
I: Retrieving gcc-5-base 5.3.1-8
I: Validating gcc-5-base 5.3.1-8
I: Retrieving gnupg 1.4.20-1
I: Validating gnupg 1.4.20-1
I: Retrieving gpgv 1.4.20-1
I: Validating gpgv 1.4.20-1
I: Retrieving grep 2.22-1
I: Validating grep 2.22-1
I: Retrieving gzip 1.6-4
I: Validating gzip 1.6-4
I: Retrieving hostname 3.16
I: Validating hostname 3.16
I: Retrieving ifupdown 0.8.10
I: Validating ifupdown 0.8.10
I: Retrieving init 1.24
I: Validating init 1.24
I: Retrieving init-system-helpers 1.24
I: Validating init-system-helpers 1.24
I: Retrieving initscripts 2.88dsf-59.2kali1
I: Validating initscripts 2.88dsf-59.2kali1
I: Retrieving insserv 1.14.0-5.2
I: Validating insserv 1.14.0-5.2
I: Retrieving iproute2 4.3.0-1
I: Validating iproute2 4.3.0-1
I: Retrieving iptables 1.6.0-2
I: Validating iptables 1.6.0-2
I: Retrieving iputils-ping 3:20121221-5+b2
I: Validating iputils-ping 3:20121221-5+b2
I: Retrieving isc-dhcp-client 4.3.3-5
I: Validating isc-dhcp-client 4.3.3-5
I: Retrieving isc-dhcp-common 4.3.3-5
I: Validating isc-dhcp-common 4.3.3-5
I: Retrieving kali-archive-keyring 2015.2
I: Validating kali-archive-keyring 2015.2
I: Retrieving kmod 22-1
I: Validating kmod 22-1
I: Retrieving libacl1 2.2.52-3
I: Validating libacl1 2.2.52-3
I: Retrieving libapparmor1 2.10-3
I: Validating libapparmor1 2.10-3
I: Retrieving libapt-inst2.0 1.2.3
I: Validating libapt-inst2.0 1.2.3
I: Retrieving libapt-pkg5.0 1.2.3
I: Validating libapt-pkg5.0 1.2.3
I: Retrieving libattr1 1:2.4.47-2
I: Validating libattr1 1:2.4.47-2
I: Retrieving libaudit-common 1:2.4.5-1
I: Validating libaudit-common 1:2.4.5-1
I: Retrieving libaudit1 1:2.4.5-1
I: Validating libaudit1 1:2.4.5-1
I: Retrieving libblkid1 2.27.1-3
I: Validating libblkid1 2.27.1-3
I: Retrieving libboost-iostreams1.58.0 1.58.0+dfsg-4.1
I: Validating libboost-iostreams1.58.0 1.58.0+dfsg-4.1
I: Retrieving libbz2-1.0 1.0.6-8
I: Validating libbz2-1.0 1.0.6-8
I: Retrieving libc-bin 2.21-7
I: Validating libc-bin 2.21-7
I: Retrieving libc6 2.21-7
I: Validating libc6 2.21-7
I: Retrieving libcap2 1:2.24-12
I: Validating libcap2 1:2.24-12
I: Retrieving libcap2-bin 1:2.24-12
I: Validating libcap2-bin 1:2.24-12
I: Retrieving libcomerr2 1.42.13-1
I: Validating libcomerr2 1.42.13-1
I: Retrieving libcryptsetup4 2:1.7.0-2kali1
I: Validating libcryptsetup4 2:1.7.0-2kali1
I: Retrieving libdb5.3 5.3.28-11
I: Validating libdb5.3 5.3.28-11
I: Retrieving libdebconfclient0 0.204
I: Validating libdebconfclient0 0.204
I: Retrieving libdevmapper1.02.1 2:1.02.115-2
I: Validating libdevmapper1.02.1 2:1.02.115-2
I: Retrieving libdns-export100 1:9.9.5.dfsg-12.1
I: Validating libdns-export100 1:9.9.5.dfsg-12.1
I: Retrieving libestr0 0.1.10-1
I: Validating libestr0 0.1.10-1
I: Retrieving libfdisk1 2.27.1-3
I: Validating libfdisk1 2.27.1-3
I: Retrieving libffi6 3.2.1-4
I: Validating libffi6 3.2.1-4
I: Retrieving libgcc1 1:5.3.1-8
I: Validating libgcc1 1:5.3.1-8
I: Retrieving libgcrypt20 1.6.4-5
I: Validating libgcrypt20 1.6.4-5
I: Retrieving libgdbm3 1.8.3-13.1
I: Validating libgdbm3 1.8.3-13.1
I: Retrieving libgmp10 2:6.1.0+dfsg-2
I: Validating libgmp10 2:6.1.0+dfsg-2
I: Retrieving libgnutls-openssl27 3.4.9-2
I: Validating libgnutls-openssl27 3.4.9-2
I: Retrieving libgnutls30 3.4.9-2
I: Validating libgnutls30 3.4.9-2
I: Retrieving libgpg-error0 1.21-1
I: Validating libgpg-error0 1.21-1
I: Retrieving libhogweed4 3.2-1
I: Validating libhogweed4 3.2-1
I: Retrieving libicu55 55.1-7
I: Validating libicu55 55.1-7
I: Retrieving libidn11 1.32-3
I: Validating libidn11 1.32-3
I: Retrieving libisc-export95 1:9.9.5.dfsg-12.1
I: Validating libisc-export95 1:9.9.5.dfsg-12.1
I: Retrieving libjson-c2 0.11-4
I: Validating libjson-c2 0.11-4
I: Retrieving libkmod2 22-1
I: Validating libkmod2 22-1
I: Retrieving liblocale-gettext-perl 1.07-1+b1
I: Validating liblocale-gettext-perl 1.07-1+b1
I: Retrieving liblogging-stdlog0 1.0.5-2
I: Validating liblogging-stdlog0 1.0.5-2
I: Retrieving liblognorm2 1.1.2-1.1
I: Validating liblognorm2 1.1.2-1.1
I: Retrieving liblz4-1 0.0~r131-1
I: Validating liblz4-1 0.0~r131-1
I: Retrieving liblzma5 5.1.1alpha+20120614-2.1
I: Validating liblzma5 5.1.1alpha+20120614-2.1
I: Retrieving libmnl0 1.0.3-5
I: Validating libmnl0 1.0.3-5
I: Retrieving libmount1 2.27.1-3
I: Validating libmount1 2.27.1-3
I: Retrieving libncurses5 6.0+20151024-2
I: Validating libncurses5 6.0+20151024-2
I: Retrieving libncursesw5 6.0+20151024-2
I: Validating libncursesw5 6.0+20151024-2
I: Retrieving libnetfilter-acct1 1.0.2-1.1
I: Validating libnetfilter-acct1 1.0.2-1.1
I: Retrieving libnettle6 3.2-1
I: Validating libnettle6 3.2-1
I: Retrieving libnewt0.52 0.52.18-2
I: Validating libnewt0.52 0.52.18-2
I: Retrieving libnfnetlink0 1.0.1-3
I: Validating libnfnetlink0 1.0.1-3
I: Retrieving libp11-kit0 0.23.2-3
I: Validating libp11-kit0 0.23.2-3
I: Retrieving libpam-modules 1.1.8-3.2
I: Validating libpam-modules 1.1.8-3.2
I: Retrieving libpam-modules-bin 1.1.8-3.2
I: Validating libpam-modules-bin 1.1.8-3.2
I: Retrieving libpam-runtime 1.1.8-3.2
I: Validating libpam-runtime 1.1.8-3.2
I: Retrieving libpam0g 1.1.8-3.2
I: Validating libpam0g 1.1.8-3.2
I: Retrieving libpcre3 2:8.38-1
I: Validating libpcre3 2:8.38-1
I: Retrieving libpipeline1 1.4.1-2
I: Validating libpipeline1 1.4.1-2
I: Retrieving libpopt0 1.16-10
I: Validating libpopt0 1.16-10
I: Retrieving libprocps5 2:3.3.11-3
I: Validating libprocps5 2:3.3.11-3
I: Retrieving libpsl0 0.11.0-2
I: Validating libpsl0 0.11.0-2
I: Retrieving libreadline6 6.3-8+b4
I: Validating libreadline6 6.3-8+b4
I: Retrieving libseccomp2 2.2.3-2
I: Validating libseccomp2 2.2.3-2
I: Retrieving libselinux1 2.4-3
I: Validating libselinux1 2.4-3
I: Retrieving libsemanage-common 2.4-3
I: Validating libsemanage-common 2.4-3
I: Retrieving libsemanage1 2.4-3
I: Validating libsemanage1 2.4-3
I: Retrieving libsepol1 2.4-2
I: Validating libsepol1 2.4-2
I: Retrieving libslang2 2.3.0-2+b1
I: Validating libslang2 2.3.0-2+b1
I: Retrieving libsmartcols1 2.27.1-3
I: Validating libsmartcols1 2.27.1-3
I: Retrieving libss2 1.42.13-1
I: Validating libss2 1.42.13-1
I: Retrieving libssl1.0.2 1.0.2f-2
I: Validating libssl1.0.2 1.0.2f-2
I: Retrieving libstdc++6 5.3.1-8
I: Validating libstdc++6 5.3.1-8
I: Retrieving libsystemd0 228-6
I: Validating libsystemd0 228-6
I: Retrieving libtasn1-6 4.7-3
I: Validating libtasn1-6 4.7-3
I: Retrieving libtext-charwidth-perl 0.04-7+b5
I: Validating libtext-charwidth-perl 0.04-7+b5
I: Retrieving libtext-iconv-perl 1.7-5+b3
I: Validating libtext-iconv-perl 1.7-5+b3
I: Retrieving libtext-wrapi18n-perl 0.06-7.1
I: Validating libtext-wrapi18n-perl 0.06-7.1
I: Retrieving libtinfo5 6.0+20151024-2
I: Validating libtinfo5 6.0+20151024-2
I: Retrieving libudev1 228-6
I: Validating libudev1 228-6
I: Retrieving libusb-0.1-4 2:0.1.12-28
I: Validating libusb-0.1-4 2:0.1.12-28
I: Retrieving libustr-1.0-1 1.0.4-5
I: Validating libustr-1.0-1 1.0.4-5
I: Retrieving libuuid1 2.27.1-3
I: Validating libuuid1 2.27.1-3
I: Retrieving libxapian22v5 1.2.22-1
I: Validating libxapian22v5 1.2.22-1
I: Retrieving libxtables11 1.6.0-2
I: Validating libxtables11 1.6.0-2
I: Retrieving login 1:4.2-3.1
I: Validating login 1:4.2-3.1
I: Retrieving logrotate 3.8.7-2
I: Validating logrotate 3.8.7-2
I: Retrieving lsb-base 9.20160110
I: Validating lsb-base 9.20160110
I: Retrieving mawk 1.3.3-17+b1
I: Validating mawk 1.3.3-17+b1
I: Retrieving mount 2.27.1-3
I: Validating mount 2.27.1-3
I: Retrieving multiarch-support 2.21-7
I: Validating multiarch-support 2.21-7
I: Retrieving nano 2.5.1-1
I: Validating nano 2.5.1-1
I: Retrieving ncurses-base 6.0+20151024-2
I: Validating ncurses-base 6.0+20151024-2
I: Retrieving ncurses-bin 6.0+20151024-2
I: Validating ncurses-bin 6.0+20151024-2
I: Retrieving net-tools 1.60+git20150829.73cef8a-2
I: Validating net-tools 1.60+git20150829.73cef8a-2
I: Retrieving netbase 5.3
I: Validating netbase 5.3
I: Retrieving netcat-traditional 1.10-41
I: Validating netcat-traditional 1.10-41
I: Retrieving nfacct 1.0.1-1.1
I: Validating nfacct 1.0.1-1.1
I: Retrieving passwd 1:4.2-3.1
I: Validating passwd 1:4.2-3.1
I: Retrieving paxctld 1.0-1
I: Validating paxctld 1.0-1
I: Retrieving perl-base 5.22.1-7
I: Validating perl-base 5.22.1-7
I: Retrieving procps 2:3.3.11-3
I: Validating procps 2:3.3.11-3
I: Retrieving readline-common 6.3-8
I: Validating readline-common 6.3-8
I: Retrieving rsyslog 8.16.0-1
I: Validating rsyslog 8.16.0-1
I: Retrieving sed 4.2.2-6.1
I: Validating sed 4.2.2-6.1
I: Retrieving sensible-utils 0.0.9
I: Validating sensible-utils 0.0.9
I: Retrieving startpar 0.59-3
I: Validating startpar 0.59-3
I: Retrieving systemd 228-6
I: Validating systemd 228-6
I: Retrieving systemd-sysv 228-6
I: Validating systemd-sysv 228-6
I: Retrieving sysv-rc 2.88dsf-59.2kali1
I: Validating sysv-rc 2.88dsf-59.2kali1
I: Retrieving sysvinit-utils 2.88dsf-59.2kali1
I: Validating sysvinit-utils 2.88dsf-59.2kali1
I: Retrieving tar 1.28-2.1
I: Validating tar 1.28-2.1
I: Retrieving tasksel 3.34
I: Validating tasksel 3.34
I: Retrieving tasksel-data 3.34
I: Validating tasksel-data 3.34
I: Retrieving traceroute 1:2.0.21-1
I: Validating traceroute 1:2.0.21-1
I: Retrieving tzdata 2016a-1
I: Validating tzdata 2016a-1
I: Retrieving udev 228-6
I: Validating udev 228-6
I: Retrieving util-linux 2.27.1-3
I: Validating util-linux 2.27.1-3
I: Retrieving vim-common 2:7.4.963-1+b1
I: Validating vim-common 2:7.4.963-1+b1
I: Retrieving vim-tiny 2:7.4.963-1+b1
I: Validating vim-tiny 2:7.4.963-1+b1
I: Retrieving wget 1.17.1-1+b1
I: Validating wget 1.17.1-1+b1
I: Retrieving whiptail 0.52.18-2
I: Validating whiptail 0.52.18-2
I: Retrieving zlib1g 1:1.2.8.dfsg-2+b1
I: Validating zlib1g 1:1.2.8.dfsg-2+b1
I: Chosen extractor for .deb packages: dpkg-deb
I: Extracting adduser...
I: Extracting base-files...
I: Extracting base-passwd...
I: Extracting bash...
I: Extracting bsdutils...
I: Extracting coreutils...
I: Extracting dash...
I: Extracting debconf...
I: Extracting debconf-i18n...
I: Extracting debianutils...
I: Extracting diffutils...
I: Extracting dmsetup...
I: Extracting dpkg...
I: Extracting e2fslibs...
I: Extracting e2fsprogs...
I: Extracting findutils...
I: Extracting gcc-4.8-base...
I: Extracting gcc-4.9-base...
I: Extracting gcc-5-base...
I: Extracting grep...
I: Extracting gzip...
I: Extracting hostname...
I: Extracting init...
I: Extracting initscripts...
I: Extracting insserv...
I: Extracting libacl1...
I: Extracting libapparmor1...
I: Extracting libattr1...
I: Extracting libaudit-common...
I: Extracting libaudit1...
I: Extracting libblkid1...
I: Extracting libbz2-1.0...
I: Extracting libc-bin...
I: Extracting libc6...
I: Extracting libcap2...
I: Extracting libcap2-bin...
I: Extracting libcomerr2...
I: Extracting libcryptsetup4...
I: Extracting libdb5.3...
I: Extracting libdebconfclient0...
I: Extracting libdevmapper1.02.1...
I: Extracting libfdisk1...
I: Extracting libgcc1...
I: Extracting libgcrypt20...
I: Extracting libgpg-error0...
I: Extracting libkmod2...
I: Extracting liblocale-gettext-perl...
I: Extracting liblzma5...
I: Extracting libmount1...
I: Extracting libncurses5...
I: Extracting libncursesw5...
I: Extracting libpam-modules...
I: Extracting libpam-modules-bin...
I: Extracting libpam-runtime...
I: Extracting libpam0g...
I: Extracting libpcre3...
I: Extracting libseccomp2...
I: Extracting libselinux1...
I: Extracting libsemanage-common...
I: Extracting libsemanage1...
I: Extracting libsepol1...
I: Extracting libsmartcols1...
I: Extracting libss2...
I: Extracting libsystemd0...
I: Extracting libtext-charwidth-perl...
I: Extracting libtext-iconv-perl...
I: Extracting libtext-wrapi18n-perl...
I: Extracting libtinfo5...
I: Extracting libudev1...
I: Extracting libustr-1.0-1...
I: Extracting libuuid1...
I: Extracting login...
I: Extracting lsb-base...
I: Extracting mawk...
I: Extracting mount...
I: Extracting multiarch-support...
I: Extracting ncurses-base...
I: Extracting ncurses-bin...
I: Extracting passwd...
I: Extracting perl-base...
I: Extracting sed...
I: Extracting sensible-utils...
I: Extracting startpar...
I: Extracting systemd...
I: Extracting systemd-sysv...
I: Extracting sysv-rc...
I: Extracting sysvinit-utils...
I: Extracting tar...
I: Extracting tzdata...
I: Extracting util-linux...
I: Extracting zlib1g...
I: Keyring file not available at /usr/share/keyrings/kali-archive-keyring.gpg; switching to https mirror https://mirrors.kernel.org/debian
dpkg-divert: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing description
dpkg-divert: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing architecture
Adding 'local diversion of /usr/sbin/invoke-rc.d to /usr/sbin/invoke-rc.d.chroot'
/third-stage: line 7: apt-get: command not found
/third-stage: line 8: apt-get: command not found
/third-stage: line 12: apt-get: command not found
/third-stage: line 13: apt-get: command not found
/third-stage: line 14: apt-get: command not found

**Comment by steev** [comment]
And what is your host machine?  Did you make some modifications to the script at all?

**Comment by crazypenguin** [comment]
i am using kali-rolling updated
don't change script at all
and i surely can chroot in,but don't find apt* in any */bin or */sbin directory

**Comment by steev** [comment]
I mean what is your host machine - is it a VMWare image, is it an amd64 machine, i386?

**Comment by crazypenguin** [comment]
amd64 machine

**Comment by crazypenguin** [comment]
it has downloaded apt package:
I: Retrieving apt 1.2.3
I: Validating apt 1.2.3

but don't extract it:
I: Chosen extractor for .deb packages: dpkg-deb
I: Extracting adduser...
I: Extracting base-files...
I: Extracting base-passwd...
I: Extracting bash...

and "debootstrap --foreign --arch $architecture kali-rolling kali-$architecture http://$mirror/kali" control all of them,so i can't really know how it works

**Comment by steev** [comment]
it seems as though it's skipping stage2 on your system for some reason (line 49 in the script) - the stage2 is what extracts them all.  Did you run the build-deps.sh file to make sure you have everything installed?

**Comment by crazypenguin** [comment]
oh,get it
when run line 49,run "LANG=C chroot kali-$architecture /debootstrap/debootstrap --second-stage" output:
I: Keyring file not available at /usr/share/keyrings/kali-archive-keyring.gpg; switching to https mirror https://mirrors.kernel.org/debian

**Comment by steev** [comment]
I haven't seen that here, so I'm not entirely sure what's going on with it.  If you're not making any changes to the script, is there a reason not to use the prebuilt 2.1 image?

**Comment by crazypenguin** [comment]
the output is above:
"I: Extracting tzdata...
I: Extracting util-linux...
I: Extracting zlib1g...
I: Keyring file not available at /usr/share/keyrings/kali-archive-keyring.gpg; switching to https mirror https://mirrors.kernel.org/debian
dpkg-divert: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
missing description
dpkg-divert: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
missing architecture
Adding 'local diversion of /usr/sbin/invoke-rc.d to /usr/sbin/invoke-rc.d.chroot'
/third-stage: line 7: apt-get: command not found
/third-stage: line 8: apt-get: command not found
/third-stage: line 12: apt-get: command not found
/third-stage: line 13: apt-get: command not found
/third-stage: line 14: apt-get: command not found"

**Comment by crazypenguin** [comment]
the prebuilt 2.1 is running on my rpi2
i just want to make a chroot env in my amd64 laptop within kali-rolling
it need some changes to the script?

**Comment by steev** [comment]
The script doesn't do that.

What would be fastest would be to grab the sdcard from the rpi2, pop it into your amd64 laptop, and rsync the contents of the second partition (the root partition) to a folder - do it as root so that permissions stay correct. 

Then you'd copy in the qemu-static binary like what is done in the script, and then you'd be able to chroot into it.

**Comment by crazypenguin** [comment]
oh no~
but how to use this script?it cann't make chroot env and img on x86 arch?

**Comment by steev** [comment]
No, it doesn't.  It wasn't designed to.  It was designed to create an image file that you write to an sdcard and boot the raspberry pi.  

That being said, creating a script of
https://github.com/offensive-security/kali-arm-build-scripts/blob/master/rpi2.sh#L1-L149 
*should* get you a chroot but, you're on your own with that.  It isn't what the scripts were designed to do, and you're better off posting in the forums for support rather than here since this is not an issue with the script.

**Comment by steev** [comment]
Upon further research, it would appear that debootstrap is currently broken.  You can try to work around it by following what they say in this bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=813232 and I've opened a bug about it in the Kali bug tracker as well https://bugs.kali.org/view.php?id=3074

Another possible workaround is to use qemu-debootstrap in place of debootstrap but I haven't tested that to know what the syntax change would be for the debootstrap line(s).

**Comment by mchineboy** [comment]
This affects my builds currently as well. Interestingly enough it worked < 24 hours ago. Something transient in the package updates?

**Comment by crazypenguin** [comment]
thanks!
