### ISSUE TITLE
will this support this developer board firefly-rk3288

### ISSUE THREAD

**Issue by ohyeah521** [offensive-security/kali-arm-build-scripts#60]
firefly-rk3288

**Comment by steev** [comment]
I don't have a firefly-rk3288 so... unlikely unless someone else modifies a script to do so.

The easiest way to do it is to find a script that's close enough to what the firefly does, and point it to the correct kernel sources, make a config that works with the various options needed (there isn't really a script for checking that yet, I'm debating grabbing the one from lxc/docker and using that as a base), and patch for the wireless... and then make sure the various bits actually work.

Pull requests are welcome :)
