### ISSUE TITLE
bbb, SSH -  Cant login with correct password

### ISSUE THREAD

**Issue by 0xicl33n** [offensive-security/kali-arm-build-scripts#61]
login as: root
root@10.81.4.30's password: toor
Access denied
root@10.81.4.30's password: toor
Access denied
root@10.81.4.30's password: toor
Access denied
root@10.81.4.30's password: toor
Access denied
root@10.81.4.30's password: toor
Access denied
root@10.81.4.30's password: toor

debug2: we did not send a packet, disable method
debug3: authmethod_lookup password
debug3: remaining preferred: ,password
debug3: authmethod_is_enabled password
debug1: Next authentication method: password
root@10.81.4.30's password: toor
debug2: we sent a password packet, wait for reply
debug1: Authentications that can continue: publickey,password
Permission denied, please try again.
root@10.81.4.30's password: toor
debug2: we sent a password packet, wait for reply
debug1: Authentications that can continue: publickey,password
Permission denied, please try again.
root@10.81.4.30's password: toor
debug2: we sent a password packet, wait for reply
debug1: Authentications that can continue: publickey,password
debug2: we did not send a packet, disable method
debug1: No more authentication methods to try.
Permission denied (publickey,password).

I do not understand this anymore lol

**Comment by steev** [comment]
Are you sure that 10.81.4.30 is your bbb?

**Comment by 0xicl33n** [comment]
My router says the hostname of 10.81.4.30 is kali

So yes

**Comment by steev** [comment]
I'm not sure - but this is something for either the kali bug system or for the forums.  This isn't an issue with the build scripts.

**Comment by strasharo** [comment]
I guess this is actually https://github.com/offensive-security/kali-arm-build-scripts/issues/65
