### ISSUE TITLE
Support for Odroid c2?

### ISSUE THREAD

**Issue by jsl303** [offensive-security/kali-arm-build-scripts#71]
Is there any plan to release image for Odroid c2 64-bit?
http://odroid.com/dokuwiki/doku.php?id=en:odroid-c2

**Comment by steev** [comment]
There are; right now, arm64 support is very basic, so waiting on a few more things.  There is also no X11 acceleration, so it's rather slow.  But we do plan to release it as soon as it's considered ready.
