### ISSUE TITLE
No Sound in Raspberry Pi?

### ISSUE THREAD

**Issue by jsl303** [offensive-security/kali-arm-build-scripts#77]
root@kali:~# aplay -l                                                           
aplay: device_list:268: no soundcards found...
Is there way to enable Kali audio driver for pi 3 on 3.5mm audio jack?

**Comment by steev** [comment]
Have you tried following https://jeffskinnerbox.wordpress.com/2012/11/15/getting-audio-out-working-on-the-raspberry-pi/ ?

**Comment by jsl303** [comment]
Thanks for the pointer!

Adding "snd-bcm2835" to "/etc/modules" seems to work!
