### ISSUE TITLE
Odroid-C2 Installation

### ISSUE THREAD

**Issue by vladcalina95** [offensive-security/kali-arm-build-scripts#81]
Can someone please take me through all the steps of installing kali linux on and odroid-c2 (32GB emmc) once i flash the image to the emmc, i boot once and if i sudo reboot it wont work anymore. I think it has something to do with the volume size and doing the right things with the dd and fdisk tools. Can anyone please be so kind as to take me through all the exact steps of how i should prepare the emmc and how to fully install kali linux. Thank you!

**Comment by vladcalina95** [comment]
not sure how to use fdsik to allocate everything kali needs and how to allow enough space at the end or something along those lines for it to work (or so i was told)

**Comment by steev** [comment]
This issues is for issues with the build scripts.  Please use the kali forums for general linux assistance.

**Comment by vladcalina95** [comment]
Where is that at? Aslo cant you please help me with the steps of installing it correctly? Also, is microSD easier to install on than emmc?
 
Thank you in advance!

**Comment by steev** [comment]
microSD and eMMC are identical.  Please re-read through the thread in issue #76.  I will not reiterate it just because you can't be bothered to read.  If you don't know where the kali linux forums are, I'm sure a search engine could help.  Please stop commenting on closed bugs.

**Comment by vladcalina95** [comment]
still cant get kali running after reboot, please help!
