### ISSUE TITLE
Please create Kali for nanopi neo air 

### ISSUE THREAD

**Issue by sadk** [offensive-security/kali-arm-build-scripts#90]
http://wiki.friendlyarm.com/wiki/index.php/NanoPi_NEO_Air

**Comment by steev** [comment]
I do not have one of these devices, so creating an image for it can be difficult.  I'd rather make one for the 2 anyway since it's 64bit and a bit better performance-wise.

**Comment by steev** [comment]
This is also a duplicate of issue #87 so I will close this one.  I've noted the device and added it to the wishlist of supported devices.
