### ISSUE TITLE
Please adjust ARM RaspberryPi image for Pi Zero Wireless Support

### ISSUE THREAD

**Issue by lindsjer** [offensive-security/kali-arm-build-scripts#91]
It appears the new Pi Zero Wireless requires a newer kernel or firmware to support it.

Attempting to use the ARM RaspberryPi image on the new Pi Zero Wireless, it will only boot to a rainbow screen.

RetroPie had to release a similar fix for their image.

**Comment by Ty6836** [comment]
+1

**Comment by nethunteros** [comment]
https://github.com/offensive-security/kali-arm-build-scripts/blob/master/rpi0w-nexmon.sh

**Comment by steev** [comment]
Closing the issue because we now have 0w support in the pi image.
