### ISSUE TITLE
[bug] nanopi2 img not support wifi  monitor mode

### ISSUE THREAD

**Issue by sadk** [offensive-security/kali-arm-build-scripts#93]
```
root@kali:~# ifconfig wlan0 down
root@kali:~# iwconfig wlan0 mode monitor
Error for wireless request "Set Mode" (8B06) :
    SET failed on device wlan0 ; Operation not supported.
root@kali:~#
```

**Comment by steev** [comment]
Which wifi device are you using? If it's the built in one, that's a known issue as it uses a broadcom chipset.  I'm looking into using the nexmon firmware with it, but at the moment, you need to use external cards.
